### ISSUE TITLE
The spam icon is missing

### ISSUE THREAD

**Issue by darkred** [Mottie/Github-show-repo-issues#1]
Using Firefox 43.0.2 and GM 3.6.
I've noticed that the 'spam' icon (next to the issue counts) is missing.
Screenshot: 
![https://i.imgur.com/CppvybT.png](https://i.imgur.com/CppvybT.png)
(as you may see I've opted-in the [new layout for repositories](https://github.com/blog/2085-a-new-look-for-repositories)  )

PS. Very useful userscript. Thank you.

**Comment by Mottie** [comment]
Hi @darkred!

Hmm, that is odd since the icon is encoded. Are you using the latest version of the script?

Also, is this only happening in one browser? The screen shot looks like Chrome which is my usual browser and I'm seeing the icon.

**Comment by darkred** [comment]
Υε
[**@Mottie**](https://github.com/Mottie) commented on [Dec 26, 2015, 7:15 PM GMT+2](https://github.com/Mottie/Github-show-repo-issues/issues/1#issuecomment-167346899 "2015-12-26T17:15:35Z - Replied by Github Comment Enhancer"):
> Hi [@darkred](https://github.com/darkred)!
> 
> Hmm, that is odd since the icon is encoded. Are you using the latest version of the script?
Yes, v2.1.0.

> Also, is this only happening in one browser? The screen shot looks like Chrome which is my usual browser and I'm seeing the icon.
I only use Firefox (I've tried it in a clean profile too)

I just installed Chrome 47.0.2526.106 with latest Tampermonkey 3.12.58
and, yes, there the icon is displayed.

**Comment by Mottie** [comment]
Ok, this should work in Firefox now.

**Comment by darkred** [comment]
I confirm. Thank you
