### ISSUE TITLE
It doesn't work as you switch tabs (it needs a page refresh in order to work)

### ISSUE THREAD

**Issue by darkred** [Mottie/Github-show-repo-issues#2]
_(using Firefox 43.0.2 and GM 3.6)._

If you just open e.g. https://github.com/Mottie?tab=repositories then the script works ok.

But, if you navigate to, e.g. open https://github.com/Mottie
and then click the `Repositories` tab,
the issues counts are not displayed unless you refresh the page(F5).

(this is caused due to that GitHub uses the HTML5 History API)

**Comment by Mottie** [comment]
Hi @darkred!

This should work with the latest version of the userscript. The reason is wasn't before is because GitHub uses ajax to load page content instead of loading an entire page.

**Comment by darkred** [comment]
As I've written in the other issue I reported,
I just installed Chrome 47.0.2526.106 (in win10x64) with latest Tampermonkey 3.12.58
and, in Chrome the problem doesn't occur.
So, it's a Firefox-only issue.

**Comment by Mottie** [comment]
Ok, I can confirm this issue... it looks like it has something to do with using the `unsafeWindow`, so I need to do some investigation.

**Comment by Mottie** [comment]
Everything appears to be working smoothly now. Thanks for reporting this issue!

**Comment by darkred** [comment]
You're welcome! Thanks for fixing this
